name: Build Artifacts

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Set env
      run: echo "RELEASE_VERSION=147" >> $GITHUB_ENV
    - name: Fetch JRE for Steam deployment
      run: |
        echo $HOME
        mkdir ~/jdks
        cd ~/jdks
        wget https://github.com/Anuken/MindustryJreBuilds/releases/download/v1/packr.jar
    - name: Create artifacts
      env:
        JDK_DIR: /home/runner/jdks/
      run: |
        git clone --depth=1 --branch=master https://github.com/Anuken/Mindustry
        cd Mindustry
        echo "BODY=$(git rev-parse HEAD)" >> $GITHUB_ENV
        sed -i 's/applicationId "io.ity.mindustry"/applicationId "io.ity.mindustry"/g' android/build.gradle
        sed -i 's/"io.ity.mindustry"/"io.ity.mindustry"/g' android/AndroidManifest.xml
        ./gradlew pack
        ./gradlew android:assembleRelease -Pbuildversion=${RELEASE_VERSION} -PshowCommitHash --stacktrace
        mv android/build/outputs/apk/release/android-release.apk android/build/outputs/apk/release/Mindustry-Android-${RELEASE_VERSION}.apk
        echo "JDK directory: $JDK_DIR"
        echo $PWD
        ls deploy/
        
    - name: Upload Android artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        file: Mindustry/android/build/outputs/apk/release/Mindustry-Android-${{ env.RELEASE_VERSION }}.apk
